# Generated by Django 6.1.1 on 2026-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('site', 'Using this site'), ('measuring', 'Measuring your room'), ('laminate', 'Laminate'), ('lvt', 'LVT'), ('amtico', 'Amtico'), ('wood', 'Engineered & solid wood'), ('vinyl', 'Vinyl'), ('carpet', 'Carpet & carpet tiles'), ('screeding', 'Screeding & floor prep')], max_length=12)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
