# Generated by Django 6.1.1 on 2026-09-08 22:59

import django.db.models.deletion
import gallery.models
import gallery.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first in the filter bar.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', help_text='JPEG, PNG or WebP. 10MB maximum.', upload_to=gallery.models.gallery_image_upload_to, validators=[gallery.validators.validate_gallery_image], width_field='width')),
                ('title', models.CharField(max_length=120)),
                ('alt_text', models.CharField(blank=True, help_text='Short description of the photo for screen readers and search engines. Falls back to the title if left blank.', max_length=160)),
                ('is_published', models.BooleanField(default=True, verbose_name='show on site')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Ties break by newest.')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.category')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
