# Generated by Django 6.1.1 on 2026-09-10 11:14

import contact.models
import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('message', models.TextField(max_length=3000)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='A photo of you. JPEG / PNG / WebP, 3MB max.', null=True, upload_to=contact.models.contact_photo_upload_to, validators=[contact.validators.validate_contact_photo])),
                ('intro', models.TextField(blank=True, help_text='Short personal introduction shown beside the photo.')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('enquiry_recipient', models.EmailField(blank=True, help_text='Where the enquiry form sends messages. Leave blank to use the email address above.', max_length=254)),
                ('response_time', models.CharField(blank=True, default='I usually reply the same day', max_length=120)),
                ('radius_miles', models.PositiveSmallIntegerField(default=25, help_text='Coverage radius drawn on the map, in miles.')),
                ('service_area', models.CharField(blank=True, default='Chelmsford, Braintree, Witham, Maldon, Billericay, Brentwood, South Woodham Ferrers and the surrounding villages', help_text='Towns listed under “Where we cover”.', max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site contact details',
                'verbose_name_plural': 'Site contact details',
            },
        ),
    ]
