# Generated by Django 6.1.1 on 2026-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='next_available_date',
            field=models.DateField(blank=True, help_text="Shown on the Contact and Book a job pages as “Next available: <date>”. Leave blank to hide it - and it hides itself automatically once the date's passed, so it never shows something stale if you forget to update it.", null=True),
        ),
    ]
