# Generated by Django 6.1.1 on 2026-09-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_sitecontact_next_available_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontact',
            name='next_available_date',
        ),
    ]
