# Generated by Django 6.1.1 on 2026-09-07 22:30

import accounts.models
import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='PNG or JPEG, 1MB maximum.', null=True, upload_to=accounts.models.profile_image_upload_to, validators=[accounts.validators.validate_profile_image], verbose_name='profile image')),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('about', models.TextField(blank=True, verbose_name='about me')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True, verbose_name='personal website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
