# Generated by Django 6.1.1 on 2026-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='terms & privacy policy accepted'),
        ),
    ]
