# Generated by Django 6.1.1 on 2026-09-08 21:05

import django.db.models.deletion
import reviews.models
import reviews.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very good'), (5, '5 - Excellent')])),
                ('headline', models.CharField(max_length=80)),
                ('body', models.TextField(max_length=1500)),
                ('image', models.ImageField(blank=True, help_text='Optional photo of the finished work. JPEG / PNG / WebP, 4MB max.', null=True, upload_to=reviews.models.review_image_upload_to, validators=[reviews.validators.validate_review_image])),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
