"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# override=True makes the .env file authoritative in development: its values
# win over anything already in the process environment. Without it, a value
# inherited from an earlier `runserver` boot (the auto-reloader passes the
# environment to each restarted child) would shadow an edited .env.
# In production there is no .env file, so this call is a no-op and the real
# host environment variables are used as-is.
load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
# Both default to today's local-dev behaviour (DEBUG on, only localhost
# allowed) when unset, so this changes nothing until you set them. Before
# going live, set DJANGO_DEBUG=False and DJANGO_ALLOWED_HOSTS to your real
# domain(s) in the production environment.
DEBUG = os.environ.get("DJANGO_DEBUG", "True").strip().lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Cloudinary media storage (staticfiles must be listed before these).
    "cloudinary_storage",
    "cloudinary",

    "core",
    "gallery",
    "bookings",
    "accounts",
    "reviews",
    "contact",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Authentication

AUTH_USER_MODEL = "accounts.User"

# Allow logging in with either a username or an email address.
AUTHENTICATION_BACKENDS = [
    "accounts.backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "core:home"
LOGOUT_REDIRECT_URL = "core:home"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Uses the DATABASE_URL environment variable when set (e.g. the Neon
# Postgres connection string). Falls back to a local SQLite file otherwise.

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # Project rule: 6-12 chars, at least one number and one special char.
        'NAME': 'accounts.validators.SixToTwelvePasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Media files (user uploads, e.g. profile images)
# https://docs.djangoproject.com/en/6.1/topics/files/
#
# With a valid CLOUDINARY_URL (cloudinary://key:secret@cloud_name) uploads go
# to Cloudinary, inside the folder named by CLOUDINARY_FOLDER. Otherwise they
# are saved to the local media/ folder.

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

_cloudinary_url = os.environ.get("CLOUDINARY_URL", "")
_use_cloudinary = _cloudinary_url.startswith("cloudinary://") and "@" in _cloudinary_url

CLOUDINARY_STORAGE = {
    # Every upload is stored under this folder in the Cloudinary account.
    "PREFIX": os.environ.get("CLOUDINARY_FOLDER", "media"),
}

STORAGES = {
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage.MediaCloudinaryStorage"
            if _use_cloudinary
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Reject anything bigger than ~2 MB before it reaches a view; the profile
# image validator enforces the real 1 MB limit.
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Provider-agnostic SMTP. Set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in the
# environment and email is sent for real; leave them blank and email is
# printed to the runserver console instead.
#
# Defaults target Gmail (smtp.gmail.com:587, STARTTLS). Override EMAIL_HOST /
# EMAIL_PORT / EMAIL_USE_SSL for another provider, e.g. Brevo:
#   EMAIL_HOST=smtp-relay.brevo.com
#   EMAIL_PORT=587

_email_host = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
_email_port = int(os.environ.get("EMAIL_PORT", "587"))
_email_user = os.environ.get("EMAIL_HOST_USER", "")
_email_password = os.environ.get("EMAIL_HOST_PASSWORD", "")
_email_use_ssl = os.environ.get("EMAIL_USE_SSL", "").strip().lower() in {"1", "true", "yes"}

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    "J-Noon Flooring Specialist <no-reply@jnoonflooring.co.uk>",
)

if _email_user and _email_password:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": _email_host,
                "port": _email_port,
                "username": _email_user,
                "password": _email_password,
                "use_tls": not _email_use_ssl,
                "use_ssl": _email_use_ssl,
            },
        },
    }
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }


# AI quoting (bookings app)
# https://console.anthropic.com/ -> API keys
#
# With ANTHROPIC_API_KEY set, the online quote form is handled by Claude.
# Without it, the quote page invites the customer to book a call instead.
# Set QUOTING_PREVIEW=1 (DEBUG only) to preview the flow with a canned
# sample estimate and no API key / cost.

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_QUOTE_MODEL = os.environ.get("ANTHROPIC_QUOTE_MODEL", "claude-sonnet-5")
QUOTING_PREVIEW = (
    DEBUG and os.environ.get("QUOTING_PREVIEW", "").strip().lower() in {"1", "true", "yes"}
)
# How many quote requests one signed-in user may submit per day.
QUOTE_DAILY_LIMIT = int(os.environ.get("QUOTE_DAILY_LIMIT", "5"))


# Google Calendar (bookings "book a call")
# A call-back request creates an event on the fitter's calendar via a Google
# service account. Without both settings, a call request is just saved and
# emailed instead.
#   GOOGLE_CALENDAR_ID          - usually the Google account's email address
#   GOOGLE_SERVICE_ACCOUNT_JSON - the whole service-account key file, as JSON,
#                                 OR an absolute path to that .json file
GOOGLE_CALENDAR_ID = os.environ.get("GOOGLE_CALENDAR_ID", "")
GOOGLE_SERVICE_ACCOUNT_JSON = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "")
BOOKINGS_TIMEZONE = os.environ.get("BOOKINGS_TIMEZONE", "Europe/London")
CALL_DAILY_LIMIT = int(os.environ.get("CALL_DAILY_LIMIT", "3"))

# Centre of the coverage area (Chelmsford town centre) - the quoting engine
# geocodes a customer's postcode and declines anything beyond the radius set
# in the admin (SiteContact.radius_miles). Matches the Contact-page map.
BOOKINGS_COVERAGE_CENTRE = (51.7356, 0.4685)


# Customer portal ("Your projects")
# How many booking requests one signed-in user may send per day.
JOB_REQUEST_DAILY_LIMIT = int(os.environ.get("JOB_REQUEST_DAILY_LIMIT", "3"))


# Stripe (customer portal card payments)
# https://dashboard.stripe.com/apikeys  (use the TEST keys to start, then swap
# to live keys later - the code is identical).
#   STRIPE_PUBLISHABLE_KEY - pk_test_... / pk_live_...  (safe for the browser)
#   STRIPE_SECRET_KEY      - sk_test_... / sk_live_...  (server only, secret)
#   STRIPE_WEBHOOK_SECRET  - whsec_...  from the webhook endpoint you add in
#                            the Stripe dashboard (or `stripe listen` locally)
# With no keys set, the portal's "Pay now" buttons are hidden and Joseph
# records payments by hand as before.
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
