# Generated by Django 6.1.1 on 2026-09-10 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlooringRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_quotes_enabled', models.BooleanField(default=True, help_text="Master switch. Turn off to send everyone to 'book a call'.")),
                ('rate_card', models.TextField(blank=True, help_text='Your full pricing, in whatever layout suits you - the AI reads it as-is. Labour rates, subfloor prep, pattern floors, and how materials work for supply & fit. Quoting stays off until this is filled.')),
                ('quoting_rules', models.TextField(blank=True, help_text="How the AI should behave, one rule per line. e.g. 'Assume 8% wastage', 'Minimum charge is half a day', 'I don't fit on stairs'.")),
                ('contingency_pct', models.PositiveSmallIntegerField(default=10, help_text='The AI widens its range by roughly this much to stay safe.', verbose_name='estimate headroom (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote settings',
                'verbose_name_plural': 'Quote settings',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_option', models.CharField(choices=[('supply_fit', 'Supply & Fit'), ('install_only', 'Installation Only'), ('repairs', 'Repairs & Remedials')], max_length=20)),
                ('flooring_note', models.CharField(blank=True, max_length=200, verbose_name='flooring notes')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='floor area (m²)')),
                ('area_unknown', models.BooleanField(default=False)),
                ('rooms', models.CharField(blank=True, max_length=200, verbose_name='rooms / areas')),
                ('current_covering', models.CharField(blank=True, max_length=120)),
                ('subfloor_type', models.CharField(choices=[('concrete', 'Concrete'), ('floorboards', 'Timber floorboards'), ('chipboard', 'Chipboard / OSB'), ('other', 'Something else'), ('unknown', 'Not sure')], default='unknown', max_length=20)),
                ('subfloor_condition', models.CharField(choices=[('sound', 'Looks flat and sound'), ('uneven', 'Uneven / sloping / bouncy'), ('damaged', 'Damaged or damp'), ('unknown', 'Not sure')], default='unknown', max_length=20)),
                ('removal_needed', models.CharField(choices=[('yes', 'Yes, all of it'), ('some', 'Some of it'), ('no', 'No'), ('unknown', 'Not sure')], default='unknown', max_length=20)),
                ('timescale', models.CharField(choices=[('asap', 'As soon as possible'), ('soon', 'Within a month or so'), ('flexible', 'No rush / flexible')], default='soon', max_length=20)),
                ('postcode', models.CharField(max_length=12)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('awaiting_info', 'Awaiting customer answers'), ('quoted', 'Estimate given'), ('call_requested', 'Needs a call'), ('reviewed', 'Reviewed by staff')], default='new', max_length=20)),
                ('ai_questions', models.JSONField(blank=True, default=list)),
                ('ai_answers', models.JSONField(blank=True, default=dict)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('quote_low', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('quote_high', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flooring_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.flooringrate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
