# Generated by Django 6.1.1 on 2026-09-10 14:14

import bookings.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_callrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('title', models.CharField(help_text="Short name for the job, e.g. 'LVT to kitchen & hall'.", max_length=140)),
                ('summary', models.TextField(blank=True, help_text='What the work involves - shown to the customer.')),
                ('site_address', models.CharField(blank=True, help_text='Where the work is.', max_length=255)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, help_text='The price you and the customer have agreed (inc. VAT if applicable).', max_digits=9, null=True)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Non-refundable deposit that secures the booking. Comes off the balance.', max_digits=7)),
                ('start_date', models.DateField(blank=True, help_text='Agreed start date.', null=True)),
                ('status', models.CharField(choices=[('requested', 'Booking requested'), ('awaiting_deposit', 'Awaiting booking fee'), ('not_started', 'Booked - not started'), ('underway', 'Underway'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('customer_note', models.TextField(blank=True, help_text='Anything the customer said when they asked to book.', max_length=2000)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When you confirmed the price and start date.', null=True)),
                ('quote_request', models.ForeignKey(blank=True, help_text='The quote this booking came from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='bookings.quoterequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('kind', models.CharField(choices=[('deposit', 'Booking fee receipt'), ('final', 'Final invoice')], default='final', max_length=10)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('agreed_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bookings.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bookings.models.job_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.job')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('kind', models.CharField(choices=[('booking_fee', 'Booking fee (deposit)'), ('balance', 'Balance payment'), ('part', 'Part payment')], default='balance', max_length=20)),
                ('method', models.CharField(choices=[('card', 'Card (online)'), ('cash', 'Cash'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Card receipt id, bank reference, etc.', max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.job')),
            ],
            options={
                'ordering': ['received_on', 'created_at'],
            },
        ),
    ]
