# Generated by Django 6.1.1 on 2026-09-10 14:56

from django.db import migrations, models


def backfill_quote_references(apps, schema_editor):
    """Give any existing quotes a reference so they can be quoted at booking."""
    QuoteRequest = apps.get_model("bookings", "QuoteRequest")
    for pk in QuoteRequest.objects.filter(reference="").values_list("pk", flat=True):
        QuoteRequest.objects.filter(pk=pk).update(reference=f"JQ{pk:04d}")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_job_invoice_jobphoto_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='customer name'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Short code the customer can quote when booking, e.g. JQ0007.', max_length=12),
        ),
        migrations.RunPython(backfill_quote_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='site_address',
            field=models.CharField(blank=True, help_text='Where the work is.', max_length=255, verbose_name='address of works'),
        ),
    ]
