# Generated by Django 6.1.1 on 2026-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_job_contact_name_job_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='booking_fee',
        ),
        migrations.AlterField(
            model_name='job',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price you and the customer have agreed (inc. VAT if applicable). The booking fee is 20% of this.', max_digits=9, null=True),
        ),
    ]
