# Generated by Django 6.1.1 on 2026-09-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_rate_card_removal_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payments_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bookings.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
