# Generated by Django 6.1.1 on 2026-09-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_cardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_card_payment', to='bookings.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Booking fee receipt'), ('receipt', 'Payment receipt'), ('final', 'Final invoice')], default='final', max_length=10),
        ),
    ]
