# Generated by Django 6.1.1 on 2026-09-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_rate_card_finishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='beading_wanted',
            field=models.CharField(choices=[('yes', 'Yes please'), ('no', 'No thanks'), ('unknown', 'Not sure - advise me')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='door_trims',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
