# Generated by Django 6.1.1 on 2026-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_quoterequest_beading_wanted_quoterequest_door_trims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('awaiting_info', 'Awaiting customer answers'), ('quoted', 'Estimate given'), ('call_requested', 'Needs a call'), ('out_of_area', 'Outside coverage area'), ('reviewed', 'Reviewed by staff')], default='new', max_length=20),
        ),
    ]
