# Generated by Django 6.1.1 on 2026-09-11 16:24

import bookings.models
import bookings.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_quoterequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff_message', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=bookings.models.job_photo_upload_to, validators=[bookings.validators.validate_message_photo])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_staff', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.job')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
