# Generated by Django 6.1.1 on 2026-09-11 17:23

import bookings.models
import bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_jobmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphoto',
            name='image',
            field=models.ImageField(upload_to=bookings.models.job_photo_upload_to, validators=[bookings.validators.validate_job_photo]),
        ),
    ]
