# Generated by Django 6.1.1 on 2026-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_payment_amount_alter_payment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
