# Generated by Django 6.1.1 on 2026-09-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_invoice_total_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Booking fee receipt'), ('receipt', 'Payment receipt'), ('final', 'Final invoice'), ('refund', 'Refund receipt')], default='final', max_length=10),
        ),
    ]
