# Generated by Django 6.1.1 on 2026-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_invoice_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_refund_settled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='payment',
            name='settles_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card (online)'), ('cash', 'Cash'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('other', 'Other'), ('credit', 'Credit (no money sent)')], default='bank', max_length=10),
        ),
    ]
