# Generated by Django 6.1.1 on 2026-09-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_invoice_total_refund_settled_payment_settles_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=3, help_text="Roughly how many days this job will take - used to work out when you're next available. Bump it up for a bigger job than the 3-day default."),
        ),
    ]
